// Supabase Edge Function: ai-assistant
//
// Proxies chat turns to the Gemini API (free tier) using a server-side
// secret (GEMINI_API_KEY), so the key never ships inside the Flutter app.
// Deploy with:
//   supabase functions deploy ai-assistant
//   supabase secrets set GEMINI_API_KEY=...
//
// Uses Gemini's Interactions API (https://generativelanguage.googleapis.com/
// v1beta/interactions), which tracks conversation state server-side — each
// request sends only the newest user message plus the previous interaction's
// id, instead of replaying the full history.
//
// Gemini's free tier caps gemini-3.7-flash at 20 requests/minute. When a
// request is rejected for hitting that quota, this function falls back to
// Groq's free tier (openai/gpt-oss-120b, 30 requests/minute) instead of
// failing outright. Groq has no server-side conversation state, so the
// fallback uses the full chat [history] the client sends alongside the new
// message. Set GROQ_API_KEY to enable the fallback; without it, a
// rate-limited Gemini request just fails as before.
//   supabase secrets set GROQ_API_KEY=...
//
// Live web grounding uses Brave Search's free API tier (2,000 queries/month,
// no card required — https://api.search.brave.com). When the latest user
// message looks time-sensitive (prices, hours, weather, news, etc. — see
// SEARCH_TRIGGER_PATTERN), one Brave search runs and the top results are
// injected into the prompt as context. Set BRAVE_API_KEY to enable it;
// without it, or on a search failure, the assistant just answers from
// training data — search never breaks the chat.
//   supabase secrets set BRAVE_API_KEY=...
//
// Set "structuredPlaces": true to get a JSON array of place suggestions
// instead of a chat reply — used for "nice places to visit in <location>"
// lookups. In that mode "reply" is a JSON string of
// {"name": string, "description": string, "address": string | null,
// "phone": string | null, "website": string | null,
// "imageUrl": string | null,
// "reviews": {"source": string, "snippet": string, "url": string}[]}[]
// (parse it client-side); it always searches for freshness regardless of
// the message content, no "Sources" footer is appended (it would break
// JSON parsing), and each place gets a real photo via a separate Brave
// Image Search call per place — never generated by the LLM itself. Any
// phone/website the LLM left null also gets a best-effort fill, and
// "reviews" is always populated this way (see bravePlaceLookup) — pulled
// from real search results (review/aggregator sites), heuristic and not
// guaranteed accurate, but never fabricated; an empty array means none
// were found, not that the place has no reviews.
//
// Request body:  {
//   "message": string,
//   "previousInteractionId": string | null,
//   "history": { "role": "user" | "assistant", "content": string }[] | null,
//   "structuredPlaces": boolean | null
// }
// Response body: { "reply": string, "interactionId": string | null }

const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
const GEMINI_MODEL = Deno.env.get("GEMINI_MODEL") ?? "gemini-3.7-flash";
const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY");
const GROQ_MODEL = Deno.env.get("GROQ_MODEL") ?? "openai/gpt-oss-120b";
const BRAVE_API_KEY = Deno.env.get("BRAVE_API_KEY");

const BASE_SYSTEM_PROMPT =
  "You are the Ona travel assistant. Help travelers discover destinations, " +
  "plan itineraries, find restaurants and activities, and answer practical " +
  "travel questions (visas, packing, safety, budgeting). Keep replies warm, " +
  "concise, and focused on travel. You're shown in a simple mobile chat " +
  "bubble, not a markdown renderer — only use plain text, '### ' headers, " +
  "'**bold**', and '* ' bullets if you need structure; avoid nested lists, " +
  "links, tables, or other markdown.";

// Used instead of BASE_SYSTEM_PROMPT when the client asks for a structured
// place list (structuredPlaces: true) rather than a chat reply — the output
// is parsed as JSON client-side, so nothing else can go in the response.
const PLACES_SYSTEM_PROMPT =
  "You are a travel expert. Given a location, respond with ONLY a valid " +
  'JSON array (no markdown, no code fences, no other text) of exactly 6 ' +
  'objects shaped {"name": string, "description": string, "address": ' +
  'string, "phone": string | null, "website": string | null}, where ' +
  "description is one short, appealing sentence about why to visit, and " +
  "address is your best real-world street address or locality for the " +
  'place (e.g. "Ozumba Mbadiwe Ave, Victoria Island, Lagos, Nigeria") — ' +
  "never leave address blank, give your best estimate even if " +
  "approximate. For phone and website, use the provided web search " +
  "results if they give a real contact number or official site for this " +
  "specific place; otherwise use null for that field — never invent a " +
  "phone number or URL. If the location isn't a real, identifiable " +
  "place, respond with an empty array: [].";

interface HistoryMessage {
  role: string;
  content: string;
}

interface BraveResult {
  title: string;
  url: string;
  description: string;
}

// Only search for messages that plausibly need live/current info — avoids
// burning free-tier quota (and tacking on an irrelevant "Sources" footer) on
// greetings, small talk, or questions answerable from stable knowledge.
const SEARCH_TRIGGER_PATTERN =
  /\b(price|prices|cost|costs|cheap|expensive|budget|exchange rate|currency|weather|forecast|temperature|rain|snow|climate|today|tonight|tomorrow|now|currently|current|latest|recent|update|updated|news|open|opening|closed|closing|hours|schedule|timing|event|events|festival|holiday|visa|entry requirement|passport requirement|covid|advisory|safety|strike|flight|flights|book|booking|availability|available)\b/i;

function needsSearch(message: string): boolean {
  return SEARCH_TRIGGER_PATTERN.test(message);
}

/**
 * One free-tier Brave Search call for the given query. Returns an empty
 * array (never throws) on missing key, network error, or non-2xx response,
 * so a search hiccup degrades to "answer without web context" instead of
 * failing the whole chat request.
 */
async function braveSearch(query: string, count = 5): Promise<BraveResult[]> {
  if (!BRAVE_API_KEY) return [];
  try {
    const url = new URL("https://api.search.brave.com/res/v1/web/search");
    url.searchParams.set("q", query);
    url.searchParams.set("count", String(count));

    const response = await fetch(url, {
      headers: {
        Accept: "application/json",
        "X-Subscription-Token": BRAVE_API_KEY,
      },
    });
    if (!response.ok) return [];

    const data = await response.json();
    const results = data?.web?.results;
    if (!Array.isArray(results)) return [];

    return results.slice(0, count).map((result: Record<string, unknown>) => ({
      title: String(result.title ?? ""),
      url: String(result.url ?? ""),
      description: String(result.description ?? ""),
    }));
  } catch {
    return [];
  }
}

/**
 * One free-tier Brave Image Search call for [query]. Returns the first
 * result's Brave-proxied thumbnail URL (hotlink-safe, sized ~500px wide) or
 * null on any failure — missing key, timeout, network error, or no results.
 * Used only for structuredPlaces responses; the LLM itself is never asked
 * for an image URL since models routinely hallucinate broken links.
 */
async function braveImageSearch(query: string): Promise<string | null> {
  if (!BRAVE_API_KEY) return null;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8_000);
  try {
    const url = new URL("https://api.search.brave.com/res/v1/images/search");
    url.searchParams.set("q", query);
    url.searchParams.set("count", "1");

    const response = await fetch(url, {
      headers: {
        Accept: "application/json",
        "X-Subscription-Token": BRAVE_API_KEY,
      },
      signal: controller.signal,
    });
    if (!response.ok) return null;

    const data = await response.json();
    const thumbnail = data?.results?.[0]?.thumbnail?.src;
    return typeof thumbnail === "string" ? thumbnail : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

interface PlaceReview {
  source: string;
  snippet: string;
  url: string;
}

// International "+..." numbers, or "(area code) ..." numbers — deliberately
// narrow so it doesn't false-positive on postal codes, dates, or street
// numbers in a search snippet (those rarely start with '+' or use parens).
const PHONE_REGEX = /(\+\d[\d\s().-]{7,18}\d|\(\d{2,4}\)[\d\s.-]{6,14}\d)/;

// Search-result domains that are almost never a place's own official site —
// skipped when picking a "website" for a place from search results, so we
// don't point users at a review aggregator or social profile instead.
const NON_OFFICIAL_DOMAINS = [
  "tripadvisor.",
  "facebook.",
  "instagram.",
  "yelp.",
  "wikipedia.",
  "twitter.",
  "x.com",
  "youtube.",
  "pinterest.",
  "maps.google.",
];

// The subset of NON_OFFICIAL_DOMAINS (plus a couple more) whose result
// snippets are actually review/rating content worth surfacing to the user
// as "what people say" — as opposed to e.g. a Wikipedia or social page,
// which isn't a review even though it's also not the place's own site.
const REVIEW_DOMAINS = [
  "tripadvisor.",
  "yelp.",
  "google.com/maps",
  "google.com/search",
  "trustpilot.",
  "opentable.",
  "foursquare.",
];

/**
 * Best-effort phone/website/reviews lookup for one place. Phone and website
 * fill in what the LLM itself left null (it's told never to invent them);
 * reviews are always populated this way since the LLM is never asked for
 * them at all. Purely heuristic — a regex over Brave's search snippets for
 * a phone number, the first non-aggregator result for a website, and any
 * review-site results as "reviews" — so it can occasionally pick an
 * unrelated page or miss real reviews; that's an accepted trade-off for
 * "usually right" over "always blank".
 */
async function bravePlaceLookup(
  name: string,
  address: string | null,
): Promise<{
  phone: string | null;
  website: string | null;
  reviews: PlaceReview[];
}> {
  const query = address
    ? `${name} ${address} reviews contact`
    : `${name} reviews contact`;
  const results = await braveSearch(query, 5);
  if (results.length === 0) return { phone: null, website: null, reviews: [] };

  let phone: string | null = null;
  for (const r of results) {
    const match = r.description.match(PHONE_REGEX);
    if (match) {
      phone = match[1].trim();
      break;
    }
  }

  const official = results.find(
    (r) => !NON_OFFICIAL_DOMAINS.some((domain) => r.url.includes(domain)),
  );

  const reviews = results
    .filter((r) => REVIEW_DOMAINS.some((domain) => r.url.includes(domain)))
    .filter((r) => r.description.trim().length > 0)
    .slice(0, 3)
    .map((r) => ({ source: r.title, snippet: r.description, url: r.url }));

  return { phone, website: official?.url ?? null, reviews };
}

function buildSystemInstruction(
  basePrompt: string,
  searchResults: BraveResult[],
): string {
  if (searchResults.length === 0) return basePrompt;

  const context = searchResults
    .map((r, i) => `${i + 1}. ${r.title} (${r.url})\n${r.description}`)
    .join("\n\n");

  return (
    `${basePrompt}\n\n` +
    "Here are live web search results for the user's latest message. Use " +
    "them if relevant to give an up-to-date answer (prices, hours, weather, " +
    "events, news); ignore them if they don't apply. Don't mention that " +
    "you were given search results — just answer naturally.\n\n" +
    `${context}`
  );
}

/** True if a failed Gemini response looks like a free-tier quota hit. */
function isRateLimited(status: number, errorText: string): boolean {
  return (
    status === 429 ||
    /too_many_requests|RESOURCE_EXHAUSTED|quota/i.test(errorText)
  );
}

/**
 * Fallback call to Groq's free tier (OpenAI-compatible chat completions),
 * used when Gemini's free-tier rate limit is hit. Groq has no server-side
 * conversation state, so [history] (already including the newest user
 * message) is sent in full instead of a chained interaction id.
 */
async function callGroq(
  history: HistoryMessage[],
  systemInstruction: string,
): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20_000);

  let response: Response;
  try {
    response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        Authorization: `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: GROQ_MODEL,
        messages: [
          { role: "system", content: systemInstruction },
          ...history.map((m) => ({
            role: m.role === "assistant" ? "assistant" : "user",
            content: m.content,
          })),
        ],
      }),
      signal: controller.signal,
    });
  } catch (err) {
    throw new Error(
      controller.signal.aborted
        ? "Groq request timed out after 20s"
        : `Groq request failed: ${err}`,
    );
  } finally {
    clearTimeout(timeout);
  }

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Groq API error: ${errorText}`);
  }

  const data = await response.json();
  const text = data?.choices?.[0]?.message?.content;
  if (typeof text !== "string") {
    throw new Error("Unexpected response shape from Groq.");
  }
  return text;
}

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (!GEMINI_API_KEY) {
    return jsonResponse(
      { error: "GEMINI_API_KEY is not configured on this project." },
      500,
    );
  }

  try {
    const { message, previousInteractionId, history, structuredPlaces } =
      await req.json();
    if (typeof message !== "string" || message.trim().length === 0) {
      return jsonResponse({ error: "message is required" }, 400);
    }

    // Structured place lists always search (freshness matters more than
    // quota here, and it's a deliberate one-off action, not chat spam);
    // regular chat only searches when the message looks time-sensitive.
    const searchResults = structuredPlaces || needsSearch(message)
      ? await braveSearch(message)
      : [];
    const systemInstruction = buildSystemInstruction(
      structuredPlaces ? PLACES_SYSTEM_PROMPT : BASE_SYSTEM_PROMPT,
      searchResults,
    );

    // Cap how long we wait on Gemini. Without this, a stalled response from
    // Google hangs the whole function until Supabase's platform-level
    // timeout kills it — slow, and it skips the Groq fallback entirely. A
    // timeout is treated the same as a rate limit below: Gemini not
    // answering in time is effectively "unavailable" either way.
    const geminiController = new AbortController();
    const geminiTimeout = setTimeout(() => geminiController.abort(), 20_000);

    let geminiResponse: Response | null = null;
    let geminiNetworkError: string | null = null;
    try {
      geminiResponse = await fetch(
        "https://generativelanguage.googleapis.com/v1beta/interactions",
        {
          method: "POST",
          headers: {
            "content-type": "application/json",
            "x-goog-api-key": GEMINI_API_KEY,
          },
          body: JSON.stringify({
            model: GEMINI_MODEL,
            system_instruction: systemInstruction,
            input: message,
            // A lightweight chat assistant doesn't need deep reasoning —
            // keep thinking cheap so free-tier quota goes toward replies.
            generation_config: { thinking_level: "low" },
            ...(previousInteractionId
              ? { previous_interaction_id: previousInteractionId }
              : {}),
          }),
          signal: geminiController.signal,
        },
      );
    } catch (err) {
      geminiNetworkError = geminiController.signal.aborted
        ? "Gemini request timed out after 20s"
        : `Gemini request failed: ${err}`;
    } finally {
      clearTimeout(geminiTimeout);
    }

    let reply: string;
    let interactionId: string | null = null;

    if (geminiResponse?.ok) {
      const data = await geminiResponse.json();
      // The raw REST response has no top-level "output_text" — that's only
      // a convenience property in Google's SDK wrappers. The real text
      // lives in steps[].content[].text on "model_output" steps.
      const steps = Array.isArray(data.steps) ? data.steps : [];
      reply = steps
        .filter((step: { type: string }) => step.type === "model_output")
        .flatMap(
          (step: { content?: { type: string; text?: string }[] }) =>
            step.content ?? [],
        )
        .filter((block: { type: string }) => block.type === "text")
        .map((block: { text?: string }) => block.text ?? "")
        .join("")
        .trim();
      interactionId = data.id ?? null;
    } else {
      const errorText =
        geminiNetworkError ?? (await geminiResponse!.text());
      const shouldFallBack =
        geminiNetworkError !== null ||
        isRateLimited(geminiResponse!.status, errorText);
      if (!GROQ_API_KEY || !shouldFallBack) {
        return jsonResponse({ error: `Gemini API error: ${errorText}` }, 502);
      }
      // Gemini is rate-limited, timed out, or otherwise unavailable — fall
      // back to Groq using the full conversation so far. previousInteractionId
      // is left untouched: once Gemini recovers, the next turn resumes that
      // chain fresh.
      const fallbackHistory: HistoryMessage[] = Array.isArray(history)
        ? history
        : [{ role: "user", content: message }];
      try {
        reply = await callGroq(fallbackHistory, systemInstruction);
      } catch (groqError) {
        return jsonResponse(
          {
            error:
              `Gemini unavailable (${errorText}); Groq fallback also ` +
              `failed: ${groqError}`,
          },
          502,
        );
      }
    }

    if (!structuredPlaces && searchResults.length > 0) {
      const sources = searchResults
        .map((r) => `- ${r.title}: ${r.url}`)
        .join("\n");
      reply += `\n\nSources:\n${sources}`;
    }

    if (structuredPlaces) {
      // Attach a real photo to each place via Brave Image Search — never
      // ask the LLM for an image URL itself, it will hallucinate one. If
      // parsing fails for any reason, fall through and return the reply
      // as-is; the client already tolerates unparseable places responses.
      try {
        let raw = reply.trim();
        if (raw.startsWith("```")) {
          raw = raw
            .replace(/^```[a-zA-Z]*\n?/, "")
            .replace(/```$/, "")
            .trim();
        }
        const places = JSON.parse(raw);
        if (Array.isArray(places)) {
          const withImages = await Promise.all(
            places.map(async (place) => {
              if (typeof place?.name !== "string") return place;
              const address =
                typeof place?.address === "string" ? place.address : null;
              const [imageUrl, lookup] = await Promise.all([
                braveImageSearch(place.name),
                bravePlaceLookup(place.name, address),
              ]);
              return {
                ...place,
                imageUrl,
                phone: place.phone ?? lookup.phone,
                website: place.website ?? lookup.website,
                reviews: lookup.reviews,
              };
            }),
          );
          reply = JSON.stringify(withImages);
        }
      } catch {
        // Leave reply as the raw (imageless) JSON text.
      }
    }

    return jsonResponse({ reply, interactionId });
  } catch (error) {
    return jsonResponse({ error: String(error) }, 500);
  }
});
