/// Currency display names, keyed by ISO code — mirrors the set from the
/// original app so the converter shows friendly labels, not just codes.
const currencyNames = {
  'USD': 'US Dollar',
  'EUR': 'Euro',
  'GBP': 'British Pound',
  'JPY': 'Japanese Yen',
  'AUD': 'Australian Dollar',
  'CAD': 'Canadian Dollar',
  'CHF': 'Swiss Franc',
  'CNY': 'Chinese Yuan',
  'INR': 'Indian Rupee',
  'MXN': 'Mexican Peso',
  'BRL': 'Brazilian Real',
  'ZAR': 'South African Rand',
  'RUB': 'Russian Ruble',
  'KRW': 'South Korean Won',
  'SGD': 'Singapore Dollar',
  'HKD': 'Hong Kong Dollar',
  'NOK': 'Norwegian Krone',
  'SEK': 'Swedish Krona',
  'DKK': 'Danish Krone',
  'NZD': 'New Zealand Dollar',
  'TRY': 'Turkish Lira',
  'PLN': 'Polish Zloty',
  'THB': 'Thai Baht',
  'MYR': 'Malaysian Ringgit',
  'IDR': 'Indonesian Rupiah',
  'PHP': 'Philippine Peso',
  'AED': 'UAE Dirham',
  'SAR': 'Saudi Riyal',
  'ILS': 'Israeli Shekel',
  'CZK': 'Czech Koruna',
  'HUF': 'Hungarian Forint',
  'RON': 'Romanian Leu',
  'CLP': 'Chilean Peso',
  'ARS': 'Argentine Peso',
  'COP': 'Colombian Peso',
  'PEN': 'Peruvian Sol',
  'VND': 'Vietnamese Dong',
  'EGP': 'Egyptian Pound',
  'NGN': 'Nigerian Naira',
  'KES': 'Kenyan Shilling',
  'PKR': 'Pakistani Rupee',
  'BDT': 'Bangladeshi Taka',
  'UAH': 'Ukrainian Hryvnia',
};

const currencySymbols = {
  'USD': '\$',
  'EUR': '€',
  'GBP': '£',
  'JPY': '¥',
  'AUD': 'A\$',
  'CAD': 'C\$',
  'CHF': 'Fr',
  'CNY': '¥',
  'INR': '₹',
  'MXN': '\$',
  'BRL': 'R\$',
  'ZAR': 'R',
  'RUB': '₽',
  'KRW': '₩',
  'SGD': 'S\$',
  'HKD': 'HK\$',
  'NOK': 'kr',
  'SEK': 'kr',
  'DKK': 'kr',
  'NZD': 'NZ\$',
  'TRY': '₺',
  'PLN': 'zł',
  'THB': '฿',
  'MYR': 'RM',
  'IDR': 'Rp',
  'PHP': '₱',
  'AED': 'د.إ',
  'SAR': '﷼',
  'ILS': '₪',
  'CZK': 'Kč',
  'HUF': 'Ft',
  'RON': 'lei',
  'CLP': '\$',
  'ARS': '\$',
  'COP': '\$',
  'PEN': 'S/',
  'VND': '₫',
  'EGP': 'E£',
  'NGN': '₦',
  'KES': 'KSh',
  'PKR': '₨',
  'BDT': '৳',
  'UAH': '₴',
};

const popularCurrencyCodes = [
  'USD',
  'EUR',
  'GBP',
  'JPY',
  'AUD',
  'CAD',
  'CHF',
  'CNY',
  'INR',
  'MXN',
  'BRL',
  'ZAR',
];
