/// A review snippet pulled from the web for a [PlaceSuggestion] — e.g. a
/// TripAdvisor or Yelp result — attached server-side via Brave Search, never
/// generated by the LLM. Not a full review, just enough to preview it and
/// link out to the source.
class PlaceReview {
  const PlaceReview({
    required this.source,
    required this.snippet,
    required this.url,
  });

  /// The result page's title, used as a human-readable source label (e.g.
  /// "Nike Art Gallery Reviews - TripAdvisor").
  final String source;

  /// A short excerpt from the source page mentioning this place.
  final String snippet;

  /// Link to the full source page.
  final String url;

  factory PlaceReview.fromJson(Map<String, dynamic> json) {
    return PlaceReview(
      source: json['source'] as String? ?? '',
      snippet: json['snippet'] as String? ?? '',
      url: json['url'] as String? ?? '',
    );
  }

  Map<String, dynamic> toJson() => {
    'source': source,
    'snippet': snippet,
    'url': url,
  };
}
